### PR TITLE
fix: SSL_shutdown on incomplete handshake

### LINKED ISSUE #430: TlsSocket shutdown while in init
`SSL protocol error 107:336462231 shutdown while in init ../helio/util/tls/tls_engine.cc : 150 `

The problem is that we call `shutdown` during the `handshake` phase.

### PR DESCRIPTION
**Pull request by kostasrim**
We should not call `SSL_shutdown` if the handshake is not complete.

Furthermore reduce the `LOG(INFO)` because they can flood and steal cpu time.

Fixes: #430

### CODE REVIEW

File: util/tls/tls_engine.cc [hunk 1]
```diff
@@ -237,15 +236,16 @@ auto Engine::ToOpResult(int result, const char* location) -> OpResult {
...
       queue_error = ERR_get_error();
-      LOG(WARNING) << "SSL protocol error " << ERROR_DETAILS;
+      LOG_EVERY_T(WARNING, 30) << "SSL protocol error " << ERROR_DETAILS;
       break;
+    }
     default:
       queue_error = ERR_get_error();
       state_ |= FATAL_ERROR;
-      LOG(WARNING) << "Unexpected SSL error " << ssl_error << " " << ERROR_DETAILS;
+      LOG_EVERY_T(WARNING, 30) << "Unexpected SSL error " << ssl_error << " " << ERROR_DETAILS;
```
Comment (romange) [inline util/tls/tls_engine.cc:248]: same

**Review by romange — APPROVED** [review]
